version: "3.9"

services:
  api: 
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: sello-ai-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN:-http://0.0.0.0:5173}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://0.0.0.0:8000/docs"]
      interval: 15s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://0.0.0.0:8000}
    container_name: sello-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://0.0.0.0:8000}
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://0.0.0.0/"]
      interval: 30s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: sello-redis
    restart: unless-stopped
    ports:
      - "6379:6379"