services:
  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: sello-ai-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      # Browser origin that will hit the API during dev
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN:-http://localhost:5173}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/docs"]
      interval: 15s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
        - VITE_WS_BASE_URL=${VITE_WS_BASE_URL:-ws://localhost:8000}
    container_name: sello-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: sello-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
