services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.4
    restart: unless-stopped
    container_name: rag_weaviate
    ports:
      - "8085:8080"
      - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 100
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_MODULES: "text2vec-voyageai"
      VOYAGE_API_KEY: ${GEMINI_API_KEY:-"dummy-key"}

  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: sello-ai-backend
    restart: unless-stopped
    expose:
      - "8080"
    env_file:
      - ./.env
    environment:
      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN:-http://localhost:8000}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
    depends_on:
      - redis
      - weaviate
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/api/health"]
      interval: 15s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=/api
        - VITE_WS_BASE_URL=/events
    container_name: sello-frontend
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 10

  nginx:
    build: ./nginx
    container_name: sello-ai-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - frontend
      - api

  redis:
    image: redis:7-alpine
    container_name: sello-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  weaviate_data:
